language: node_js
node_js:
- node
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm i -g npm@5.7.1
- npm ci
before_deploy:
- npm run build-client # make the bundle
- rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: dev-notebook
  api_key:
    secure: hzwfMnHwqzsOYeSgfqFBTTphiSJ359/c1JfIXIogrtw4/iIl1LCIolJMO1u65ZM+iTfcJkung3gT2lbuD3gttquiSxrhTkaXksrUcgxws4RyIsFNiNCu+8u5uGYZHTvy/hXv3iQKAlDtvN5Sn7z0f7mLKBwg5M4Ofj0FRO0LcTAtVJTMkLvayVvSVLprt/VwTn3YJ51ynKspmgezXRTR6L347OtmYwX/DH+SHPzoLIJuXE+QZzowEvYOAnQV9Jx6c+NWxzQhgyT2FB1HH9dVMleMAn1A4vcdmtWgkkK3U+2AvsppuG5+8hErj/3VLtlmUfO4zF+NAK5obPDmQIU6tRCkKPVP6WEEmoMfZUrCZXEhiNYADfLn3ApFIIUCRoioWpPdeV3MBZDS1YqidLBvyhYY27fGRDjv7uKZ/oATMhVZ4YEyt3GYupGKp0OMmeNSzmgNpLEZ4lS9BQ91JIftOH0Dzvr/ebixS7TZHoLVMWiS08dmWsIZ/ChLnd+Jzmnrqx3XJoUzl0JKPKwEbLMiLB/XOkq35+fObRtGhgDYf2ougEGJmDtxKuQfFbiCsOfllt5X72wTwUOC3o2SZCtksPoxOx4MlFVnZeIdn6QOCP+r5UA2m5eO4lYeKQX5vQue5zkXS/9avVQbUDw4ICONyGGAo1LxpqnyZzCXeIheZv0=
